# Required for Jekyll.
baseurl: ""
permalink: "/blog/:year/:month/:day/:slug/"
timezone: "Etc/UTC"
theme: "minima"
url: "https://www.lujingcen.com"

# Enabled plugins.
plugins:
  - jekyll-paginate

# Pagination configuration
paginate: 5
paginate_path: "/page/:num/"

# Default front matter.
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      type: "posts"

# Sass configuration.
sass:
  style: "compressed"

# Kramdown configuration.
kramdown:
  auto_id_prefix: "header-"
  syntax_highlighter_opts:
    disable: true

# Theme-specific configurations.
author:
  name: "Lujing Cen"
  email: "lujingcen@gmail.com"
description: "A place where I document my learnings."
google_analytics: "G-0N8JV9HFGZ"
header_pages:
  - "_pages/about.md"
minima:
  social_links:
    - { platform: "github", user_url: "https://github.com/bobbyluig" }
    - { platform: "linkedin", user_url: "https://linkedin.com/in/lujing-cen/" }
show_excerpts: true
title: "Standard Output"

# Comments configuration.
giscus:
  repo: "bobbyluig/bobbyluig.github.io"
  repo_id: "R_kgDOImD8Kg"
  category_name: "Announcements"
  category_id: "DIC_kwDOImD8Ks4CTJNJ"
  theme: "light"

include:
  - "_pages"

exclude:
  - ".sass-cache/"
  - ".jekyll-cache/"
  - "gemfiles/"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules/"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
