title: Standard Output
name: Lujing Cen
description: A place where I document my learnings.
baseurl: ""
url: "https://www.lujingcen.com"
repository: "bobbyluig/bobbyluig.github.io"

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

search: true
permalink: /blog/:year/:month/:day/:slug/

defaults:
  - scope:
      path: ""
    values:
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: false
      toc_label: "Contents"

author:
  name: "Lujing Cen"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Software Engineer at Plaid"
  location: "San Francisco, CA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bobbyluig"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/lujing-cen/"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-0N8JV9HFGZ"
    anonymize_ip: true

comments:
  provider: "giscus"
  giscus:
    repo_id: "R_kgDOImD8Kg"
    category_name: "Announcements"
    category_id: "DIC_kwDOImD8Ks4CTJNJ"
    discussion_term: "pathname"
    reactions_enabled: "1"
    theme: "light"

include:
  - "_pages"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
